In [1]:
1

1

In [2]:
1.2

1.2

In [3]:
import numpy as np

In [4]:

v= [1, 2, 3, 4]
v

[1, 2, 3, 4]

In [5]:
v= np.array(v)
v

array([1, 2, 3, 4])

In [6]:
v.shape

(4,)

In [7]:
A= [[1,2,3,4],
    [5,6,7,8]]
A

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [8]:
A= np.array(A)
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
A.shape

(2, 4)

In [10]:
T=[[1,2,3,4],
   [5,6,7,8],
   [9,10,11,12],
   [13,14,15,16]]
T

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

In [11]:
T= np.array(T)
T

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
T.shape

(4, 4)

In [13]:
T= T.reshape((2,2,4))
T

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [14]:
T.shape

(2, 2, 4)

In [15]:
T[0]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
T[1]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [17]:
v.ndim

1

In [18]:
A.ndim

2

In [19]:
T.ndim

3

In [20]:
T4d= T.reshape(2,2,2,2)
T4d

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [21]:
T4d.shape

(2, 2, 2, 2)

In [22]:
v, A, T, T4d

(array([1, 2, 3, 4]),
 array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],
 
        [[ 9, 10, 11, 12],
         [13, 14, 15, 16]]]),
 array([[[[ 1,  2],
          [ 3,  4]],
 
         [[ 5,  6],
          [ 7,  8]]],
 
 
        [[[ 9, 10],
          [11, 12]],
 
         [[13, 14],
          [15, 16]]]]))

In [23]:
v

array([1, 2, 3, 4])

In [24]:
v14= v.reshape(1,4)
v14

array([[1, 2, 3, 4]])

In [25]:
v41= v.reshape(4,1)
v41

array([[1],
       [2],
       [3],
       [4]])

In [26]:
v.shape, v14.shape, v41.shape

((4,), (1, 4), (4, 1))