In [1]:
import numpy as np

In [17]:
# 1x − 2y + 3z = 1
# 2x + 1y − 1z = 3
#−1x + 1y + 2z = 7
 
#A1為=左邊的x,y,z之係數
A1 = np.array([
    [ 1, -2, 3],
    [ 2, 1, -1],
    [ -1, 1, 2 ]
    ])

#Y1為各行的=右邊之常數
Y1 = np.array([
    [1],[3],[7]
    ])

#用np求x,y,z
X1 = np.linalg.solve(A1, Y1)
print('X1=\n', X1) 

X1=
 [[0.94444444]
 [3.38888889]
 [2.27777778]]
a1 =  1.0
a2 =  2.99999999
a3 =  7.00000001


In [30]:
a5 = A1 [0]
print (a5)

[ 1 -2  3]


In [29]:
#驗算
a1 = 1 * 0.94444444 + (-2) * 3.38888889 + 3 * 2.27777778
a2 = 2 * 0.94444444 + 1 * 3.38888889 + (-1) * 2.27777778
a3 = (-1) * 0.94444444 + 1 * 3.38888889 + 2 * 2.27777778  

print('a1 = ', a1)
print('a2 = ', a2)
print('a3 = ', a3)

a1 =  1.0
a2 =  2.99999999
a3 =  7.00000001


In [20]:
# 1x − 2y + 3z + 1u − 2v = −1
# 2x + 1y − 1z − 1u + 1v =  3
#−1x + 1y + 2z + 2u (+ 3v) =  7
# 2x + 1y − 1z − 1u + 2v =  5
# 1x + 3y − 2z + 2u − 2v = −4

A2 = np.array([
    [ 1, -2, 3, 1 , -2],
    [ 2, 1, -1, -1, 1],
    [ -1, 1, 2 , 2, 3],
    [ 2, 1, -1, -1, 2],
    [ 1, 3, -2, 2, -2]
    ])

Y2 = np.array([
    [-1],[3],[7],[5],[-4]
    ])

X2 = np.linalg.solve(A2, Y2)
print('X=\n', X2) 


X=
 [[0.875]
 [0.125]
 [0.75 ]
 [0.125]
 [2.   ]]


In [32]:
b1 = 1*0.875 + (-2)*0.125 + 3*0.75 + 1*0.125 + (-2)*2
b2 = 2*0.875 + 1*0.125 + (-1)*0.75 + (-1)*0.125 + 1*2
b3 = -1*0.875 + 1*0.125 + 2*0.75 + 2*0.125 + 3*2
b4 = 2*0.875 + 1*0.125 + (-1)*0.75 + (-1)*0.125 + 2*2
b5 = 1*0.875 + 3*0.125 + (-2)*0.75 + 2*0.125 + (-2)*2

print('b1 = ', b1)
print('b2 = ', b2)
print('b3 = ', b3)
print('b4 = ', b4)
print('b5 = ', b5)

b1 =  -1.0
b2 =  3.0
b3 =  7.0
b4 =  5.0
b5 =  -4.0


In [ ]:
#方法太笨 10階就沒做了